### ISSUE TITLE
Expose additional required methods to Mission and Runtime

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-booster-catalog-service#36]
prerequisite: string;

According to https://github.com/fabric8-launcher/launcher-planning/issues/121 and https://github.com/fabric8-launcher/launcher-planning/issues/120

**Comment by quintesse** [comment]
Sure, we can do this, but are we using this anywhere? I mean I don't think it's very useful to expose all `metadata` properties as attribute if we're not going to use them in code.

In fact I think it's counter-productive.

So unless you can convince me otherwise I'd say: -1

**Comment by gastaldi** [comment]
@quintesse I am not following. https://github.com/fabric8-launcher/launcher-planning/issues/121 says that `prerequisite` should be exposed, just like `suggested`.

**Comment by quintesse** [comment]
Because the `metadata` section is a section of free user-definable values. If we were always going to define all attributes we could just as well have made them all fixed attributes. The whole idea was that UI-specific attributes could be added without having to change the code. ("You want 'starred' boosters? Well just add `stars:` to the metadata section in the catalog, add the feature to the frontend, and ready!")

Because now it's only OSIO and us. But others could be creating their own UIs at some point. It's not very logical to just start adding all those attributes and end up with the kitchen sink of attributes that the BCS doesn't care about.

And if we need to write backend code that needs those values (really use them, not just to pass them on in a REST result) then we simply get the value from the `metadata` map.

Now, if at some point some attributes are so much used and so generically useful that we're using them all over the code then we can always think about adding those.

**Comment by quintesse** [comment]
Btw, to make it more clear: my idea for the BoosterCatalog REST APIs is to just copy the entire contents of the `metadata` section into the result.

**Comment by gastaldi** [comment]
+1 let's do this

**Comment by quintesse** [comment]
Done a long time ago already.
